Fix table sort bugs
Prompt:
There are two bugs with sorting the bookmarks pane (which I just re-enabled -- maybe I disabled it because it was broken):

(1) When the list is repopulated, we're ignoring the configured sort order, so it gets reverted to alphabetical descending by name, even though the chevron showing the sort in the UI doesn't change
(2) If you try to sort by tags, you get

DEBUG: Sorting by this column is not supported.
Traceback (most recent call last):
  File "/home/soren/cabinet/Me/Software/Active/rabbitmark/rabbitmark/gui/bookmark_table.py", line 96, in sort
    self.L.sort(key=self.ModelColumn(col).sort_function(), reverse=rev)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

Sort for tags should work by alphabetizing the tags (I think we've already done that to be able to show them, right?) and sorting alphabetically by that string.

---

- Let's make the sort by tags case-insensitive
- My first click on the sort indicator on "Name" does nothing (it's starting with the arrow pointing up, which I think is backwards?)